apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    stops vm instance for a chaos duration
kind: ChaosExperiment
metadata:
  name: vm-delete
spec:
  definition:
    scope: Namespaced
    permissions: [{'apiGroups': ['', 'batch', 'litmuschaos.io'], 'resources': ['secrets' ,'jobs', 'pods', 'chaosengines', 'chaosexperiments', 'chaosresults','évents'], 'verbs': ['create', 'list', 'get', 'update', 'patch', 'delete']}]
    image: "litmuschaos/ansible-runner:latest"
    imagePullPolicy: Always
    args:
    - -c
    - ansible-playbook ./experiments/vmware/vm-delete/vm-delete_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:
    - name: VCENTERSERVER
      valueFrom:
        secretKeyRef:
          name: vcenter-secret
          key: VCENTERSERVER

    - name: VCENTERUSER
      valueFrom:
        secretKeyRef:
          name: vcenter-secret
          key: VCENTERUSER

    - name: VCENTERPASS
      valueFrom:
        secretKeyRef:
          name: vcenter-secret
          key: VCENTERPASS

    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

    - name: TOTAL_CHAOS_DURATION
      value: '' 

    - name: LIB
      value: ''

    - name: RAMP_TIME
      value: ''
      
    labels:
      experiment: vm-delete 
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
